# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://www.andreavaghi.com
enforce_ssl: www.andreavaghi.com
baseurl: /
title: Andrea Vaghi
author: Andrea Vaghi
description: Personal blog and resume
avatar: Andrea-Portrait-White.jpg
email: andrea@andreavaghi.dev
github: andreavaghi # username
twitter: andreavaghi
linkedin: andrea-vaghi-b3036935
stackoverflow: users/2350339/urbando   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
# disqus: username
google_analytics: UA-18436516-1


# needed for travis-ci build
exclude: [vendor]
