# Site settings
title: Andrea Vaghi
email: andrea.vaghi@gmail.com
description: |
  Front End Developer.
  Love travels, LEGO and penguins.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andreavaghi.com" # the base hostname & protocol for your site
twitter_username: andreavaghi
github_username:  andreavaghi
permalink: pretty
paginate_path: "/blog/page:num"

# Build settings
markdown: kramdown
