# Site settings
title: Your awesome title
email: andrea.vaghi@gmail.com
description: |
  Front End Engineer @jobrapido.com
  Love travels, LEGO and penguins
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andreavaghi.com" # the base hostname & protocol for your site
twitter_username: andreavaghi
github_username:  andreavaghi
permalink: pretty

# Build settings
markdown: kramdown
